project_id = "tbqreletxtzaosvyyvnv"

[functions.check-reminders]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false

[functions.stripe-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.stripe-portal]
verify_jwt = false

[functions.admin-get-users]
verify_jwt = false

[functions.stripe-revenue]
verify_jwt = false
